// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qortiqdnuhrjdoiiibzc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFvcnRpcWRudWhyamRvaWlpYnpjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk3ODU3MzAsImV4cCI6MjA2NTM2MTczMH0.OJaRB3ohypHiMZdJITWV7ofde3jVULE2R8GAo29H_70";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);